version: "3.9"
services:
  app:
    container_name: app_home_budget

    restart: always
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py

    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    container_name: postgres_home_budget

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=HomeBudget
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ./data/db:/var/lib/postgresql/data
